// <auto-generated />
using System;
using Citas.Infrastructure.Persistencia;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Citas.Infrastructure.Persistencia.Migraciones
{
    [DbContext(typeof(CitasDbContext))]
    [Migration("20260731223242_SeedMedicosYPacientes")]
    partial class SeedMedicosYPacientes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.29")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Citas.Domain.Entidades.Cita", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaHoraFin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaHoraInicio")
                        .HasColumnType("datetime2");

                    b.Property<int>("MedicoId")
                        .HasColumnType("int");

                    b.Property<int>("PacienteId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PacienteId");

                    b.HasIndex("MedicoId", "FechaHoraInicio");

                    b.ToTable("Citas");
                });

            modelBuilder.Entity("Citas.Domain.Entidades.Medico", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Especialidad")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Medicos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activo = true,
                            Especialidad = "Pediatría",
                            NombreCompleto = "Dra. Ana Pérez"
                        },
                        new
                        {
                            Id = 2,
                            Activo = true,
                            Especialidad = "Cardiología",
                            NombreCompleto = "Dr. Carlos Ramírez"
                        },
                        new
                        {
                            Id = 3,
                            Activo = true,
                            Especialidad = "Dermatología",
                            NombreCompleto = "Dra. Lucía Fernández"
                        },
                        new
                        {
                            Id = 4,
                            Activo = true,
                            Especialidad = "Traumatología",
                            NombreCompleto = "Dr. Miguel Torres"
                        },
                        new
                        {
                            Id = 5,
                            Activo = true,
                            Especialidad = "Ginecología",
                            NombreCompleto = "Dra. Sofía Gómez"
                        });
                });

            modelBuilder.Entity("Citas.Domain.Entidades.Paciente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("Pacientes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activo = true,
                            Email = "juan.lopez@correo.com",
                            NombreCompleto = "Juan López",
                            Telefono = "6621234567"
                        },
                        new
                        {
                            Id = 2,
                            Activo = true,
                            Email = "maria.hernandez@correo.com",
                            NombreCompleto = "María Hernández",
                            Telefono = "6627654321"
                        },
                        new
                        {
                            Id = 3,
                            Activo = true,
                            Email = "pedro.sanchez@correo.com",
                            NombreCompleto = "Pedro Sánchez",
                            Telefono = "6621112233"
                        },
                        new
                        {
                            Id = 4,
                            Activo = true,
                            Email = "laura.martinez@correo.com",
                            NombreCompleto = "Laura Martínez",
                            Telefono = "6624445566"
                        },
                        new
                        {
                            Id = 5,
                            Activo = true,
                            Email = "roberto.diaz@correo.com",
                            NombreCompleto = "Roberto Díaz",
                            Telefono = "6627778899"
                        },
                        new
                        {
                            Id = 6,
                            Activo = true,
                            Email = "carmen.ruiz@correo.com",
                            NombreCompleto = "Carmen Ruiz",
                            Telefono = "6620001122"
                        },
                        new
                        {
                            Id = 7,
                            Activo = true,
                            Email = "fernando.castro@correo.com",
                            NombreCompleto = "Fernando Castro",
                            Telefono = "6623334455"
                        },
                        new
                        {
                            Id = 8,
                            Activo = true,
                            Email = "patricia.morales@correo.com",
                            NombreCompleto = "Patricia Morales",
                            Telefono = "6626667788"
                        });
                });

            modelBuilder.Entity("Citas.Domain.Entidades.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NombreUsuario")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("NombreUsuario")
                        .IsUnique();

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activo = true,
                            Nombre = "Administrador",
                            NombreUsuario = "admin",
                            PasswordHash = "$2a$11$oX8FybCxSeGMeAtWOuctxOZNJu1ckCuWEcBiy0fz5Ll/vZ8VPfC6q"
                        });
                });

            modelBuilder.Entity("Citas.Domain.Entidades.Cita", b =>
                {
                    b.HasOne("Citas.Domain.Entidades.Medico", "Medico")
                        .WithMany("Citas")
                        .HasForeignKey("MedicoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Citas.Domain.Entidades.Paciente", "Paciente")
                        .WithMany("Citas")
                        .HasForeignKey("PacienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Medico");

                    b.Navigation("Paciente");
                });

            modelBuilder.Entity("Citas.Domain.Entidades.Medico", b =>
                {
                    b.Navigation("Citas");
                });

            modelBuilder.Entity("Citas.Domain.Entidades.Paciente", b =>
                {
                    b.Navigation("Citas");
                });
#pragma warning restore 612, 618
        }
    }
}
